AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: 'GraphQL Wroclaw Lambdas'

#############
# RESOURCES #
#############
Resources:
  ###########
  # Lambdas #
  ###########
  FlightPriceLoaderLambda:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 30
      MemorySize: 128
      InlineCode: |
        exports.handler = async(input, context, callback) => {
            console.log(input, context, callback);

            return 20 + Math.random() * 30;
        };

###########
# OUTPUTS #
###########
Outputs:
  FlightPriceLoaderLambdaName:
    Description: 'Flight price lambda name'
    Value: !Ref FlightPriceLoaderLambda
    Export:
      Name: 'GRAPHQL-WROCLAW-FLIGHT-PRICE-LAMBDA-NAME'

  FlightPriceLoaderLambdaArn:
    Description: 'Flight price lambda arn'
    Value: !GetAtt FlightPriceLoaderLambda.Arn
    Export:
      Name: 'GRAPHQL-WROCLAW-FLIGHT-PRICE-LAMBDA-ARN'

  FlightPriceLoaderLambdaRoleLogicalId:
    Description: 'Flight price lambda role logical id'
    Value: !Ref FlightPriceLoaderLambdaRole
    Export:
      Name: 'GRAPHQL-WROCLAW-FLIGHT-PRICE-LAMBDA-ROLE-LOGICAL-ID'

  FlightPriceLoaderLambdaRoleId:
    Description: 'Flight price lambda role id'
    Value: !GetAtt FlightPriceLoaderLambdaRole.RoleId
    Export:
      Name: 'GRAPHQL-WROCLAW-FLIGHT-PRICE-LAMBDA-ROLE-ID'

  FlightPriceLoaderLambdaRoleArn:
    Description: 'Flight price lambda role arn'
    Value: !GetAtt FlightPriceLoaderLambdaRole.Arn
    Export:
      Name: 'GRAPHQL-WROCLAW-FLIGHT-PRICE-LAMBDA-ROLE-ARN'