AWSTemplateFormatVersion: "2010-09-09"
Description: "GraphQL Wroclaw Elasticsearch cluster"

##############################################################################
# RESOURCES
##############################################################################
Resources:
  EsDomain:
    Type: "AWS::Elasticsearch::Domain"
    Properties:
      DomainName: 'graphql-wroclaw-es'
      ElasticsearchVersion: 6.4
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: "false"
        InstanceCount: 1
        ZoneAwarenessEnabled: "false"
        InstanceType: 't2.small.elasticsearch'
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: "true"
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
      SnapshotOptions:
        AutomatedSnapshotStartHour: "0"
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                - '294104603975'
            Action: "es:*"
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/graphql-wroclaw-es/*'
          - Effect: "Allow"
            Principal:
              AWS:
                - 'arn:aws:iam::294104603975:role/service-role/CognitoAccessForAmazonES'
            Action: "es:*"
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/graphql-wroclaw-es/*'
          - Effect: "Allow"
            Principal:
              AWS:
                - 'arn:aws:iam::294104603975:role/GRAPHQL-WROCLAW-APPSYNC-ROUTES-ELASTICSEARCH-ROLE'
            Action: "es:*"
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/graphql-wroclaw-es/*'

  ClusterStatusRedAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      # As on https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html
      AlarmDescription: 'Shards not allocated to the cluster'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ClientId
          Value: !Ref 'AWS::AccountId'
        - Name: DomainName
          Value: !Ref EsDomain
      MetricName: 'ClusterStatus.red'
      Namespace: 'AWS/ES'
      AlarmActions:
        - Fn::ImportValue: 'GRAPHQL-WROCLAW-ALARMS-SNS'
      OKActions:
        - Fn::ImportValue: 'GRAPHQL-WROCLAW-ALARMS-SNS'
      EvaluationPeriods: 1
      Period: 60
      Statistic: Maximum
      Threshold: 0

  ClusterFreeStorageSpaceTooLowAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Free storage on cluster is too low'
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: ClientId
          Value: !Ref 'AWS::AccountId'
        - Name: DomainName
          Value: !Ref EsDomain
      MetricName: 'FreeStorageSpace'
      Namespace: 'AWS/ES'
      AlarmActions:
        - Fn::ImportValue: 'GRAPHQL-WROCLAW-ALARMS-SNS'
      OKActions:
        - Fn::ImportValue: 'GRAPHQL-WROCLAW-ALARMS-SNS'
      EvaluationPeriods: 1
      Period: 60
      Statistic: Minimum
      Threshold: 100

Outputs:

  EsDomainLogicalId:
    Description: 'Es domain logical id'
    Value: !Ref EsDomain
    Export:
      Name: 'GRAPHQL-WROCLAW-ES-DOMAIN-NAME'

  EsDomainArn:
    Description: 'Es domain endpoint'
    Value: !GetAtt EsDomain.Arn
    Export:
      Name: 'GRAPHQL-WROCLAW-ES-DOMAIN-ARN'

  EsDomainEndpoint:
    Description: 'Es domain endpoint'
    Value: !GetAtt EsDomain.DomainEndpoint
    Export:
      Name: 'GRAPHQL-WROCLAW-ES-DOMAIN-ENDPOINT'
